// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: blocks.sql

package sqlcgen

import (
	"context"
	"time"
)

const getBlockByHash = `-- name: GetBlockByHash :one
SELECT block_number, block_hash, parent_hash, block_time, network, created_at FROM blocks
WHERE network = $1 AND block_hash = $2
`

type GetBlockByHashParams struct {
	Network   string `json:"network"`
	BlockHash string `json:"block_hash"`
}

func (q *Queries) GetBlockByHash(ctx context.Context, arg GetBlockByHashParams) (Block, error) {
	row := q.db.QueryRow(ctx, getBlockByHash, arg.Network, arg.BlockHash)
	var i Block
	err := row.Scan(
		&i.BlockNumber,
		&i.BlockHash,
		&i.ParentHash,
		&i.BlockTime,
		&i.Network,
		&i.CreatedAt,
	)
	return i, err
}

const getBlockByNumber = `-- name: GetBlockByNumber :one
SELECT block_number, block_hash, parent_hash, block_time, network, created_at FROM blocks
WHERE network = $1 AND block_number = $2
`

type GetBlockByNumberParams struct {
	Network     string `json:"network"`
	BlockNumber int64  `json:"block_number"`
}

func (q *Queries) GetBlockByNumber(ctx context.Context, arg GetBlockByNumberParams) (Block, error) {
	row := q.db.QueryRow(ctx, getBlockByNumber, arg.Network, arg.BlockNumber)
	var i Block
	err := row.Scan(
		&i.BlockNumber,
		&i.BlockHash,
		&i.ParentHash,
		&i.BlockTime,
		&i.Network,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestBlock = `-- name: GetLatestBlock :one
SELECT block_number, block_hash, parent_hash, block_time, network, created_at FROM blocks
WHERE network = $1
ORDER BY block_number DESC
LIMIT 1
`

func (q *Queries) GetLatestBlock(ctx context.Context, network string) (Block, error) {
	row := q.db.QueryRow(ctx, getLatestBlock, network)
	var i Block
	err := row.Scan(
		&i.BlockNumber,
		&i.BlockHash,
		&i.ParentHash,
		&i.BlockTime,
		&i.Network,
		&i.CreatedAt,
	)
	return i, err
}

const insertBlock = `-- name: InsertBlock :exec
INSERT INTO blocks (block_number, block_hash, parent_hash, block_time, network)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (network, block_number) DO NOTHING
`

type InsertBlockParams struct {
	BlockNumber int64     `json:"block_number"`
	BlockHash   string    `json:"block_hash"`
	ParentHash  string    `json:"parent_hash"`
	BlockTime   time.Time `json:"block_time"`
	Network     string    `json:"network"`
}

func (q *Queries) InsertBlock(ctx context.Context, arg InsertBlockParams) error {
	_, err := q.db.Exec(ctx, insertBlock,
		arg.BlockNumber,
		arg.BlockHash,
		arg.ParentHash,
		arg.BlockTime,
		arg.Network,
	)
	return err
}
