// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"time"
)

type Block struct {
	BlockNumber int64     `json:"block_number"`
	BlockHash   string    `json:"block_hash"`
	ParentHash  string    `json:"parent_hash"`
	BlockTime   time.Time `json:"block_time"`
	Network     string    `json:"network"`
	CreatedAt   time.Time `json:"created_at"`
}
