// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"context"
)

type Querier interface {
	GetBlockByHash(ctx context.Context, arg GetBlockByHashParams) (Block, error)
	GetBlockByNumber(ctx context.Context, arg GetBlockByNumberParams) (Block, error)
	GetLatestBlock(ctx context.Context, network string) (Block, error)
	InsertBlock(ctx context.Context, arg InsertBlockParams) error
}

var _ Querier = (*Queries)(nil)
